// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiC.Models;

namespace SiC.Migrations
{
    [DbContext(typeof(SiCContext))]
    partial class SiCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiC.Models.Acabamento", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Acabamentos");
                });

            modelBuilder.Entity("SiC.Models.AcabamentosMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AcabamentoId");

                    b.Property<long>("MaterialAcabamentoId");

                    b.HasKey("Id");

                    b.ToTable("AcabamentosMaterial");
                });

            modelBuilder.Entity("SiC.Models.Categoria", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Descricao");

                    b.Property<long>("SuperCategoriaId");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SiC.Models.Dimensao", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("altura");

                    b.Property<long>("alturaMax");

                    b.Property<long>("alturaMin");

                    b.Property<long>("largura");

                    b.Property<long>("larguraMax");

                    b.Property<long>("larguraMin");

                    b.Property<long>("profundidade");

                    b.Property<long>("profundidadeMax");

                    b.Property<long>("profundidadeMin");

                    b.HasKey("Id");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("SiC.Models.MateriaisProduto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MaterialAcabamentoId");

                    b.Property<long>("ProdutoId");

                    b.HasKey("Id");

                    b.ToTable("MateriaisProduto");
                });

            modelBuilder.Entity("SiC.Models.Material", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("SiC.Models.MaterialAcabamento", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("MaterialId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("MateriaisAcabamentos");
                });

            modelBuilder.Entity("SiC.Models.Partes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Obrigatoria");

                    b.Property<long>("ParteId");

                    b.Property<long>("ProdutoId");

                    b.HasKey("Id");

                    b.ToTable("Partes");
                });

            modelBuilder.Entity("SiC.Models.Produto", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("CategoriaId");

                    b.Property<string>("Nome");

                    b.Property<long>("Preco");

                    b.Property<bool>("RestringirMateriais");

                    b.Property<long>("maxTaxaAtual");

                    b.Property<long>("maxTaxaOcupacao");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SiC.Models.SubCategoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoriaId");

                    b.Property<long>("SubCatId");

                    b.HasKey("Id");

                    b.ToTable("SubCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
